name: Main

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"
jobs:
  build:
    runs-on: ubuntu-latest
    name: Bump version
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Retrieve Semver
        id: retrieved_semver
        run: |
          TAGNAME="${{github.ref_name}}"
          SEMVER="${TAGNAME:1}"
          echo "SEMVER=$SEMVER" >> $GITHUB_OUTPUT
      - name: Change version in Cargo.toml
        run: |
          # Change version in Cargo.toml, only replace the first occurrence -> @see https://sed.js.org/
          sed -i '0,/version = \".*\"/s//version = "${{steps.retrieved_semver.outputs.SEMVER}}"/' Cargo.toml
      - name: Create pull request
        uses: peter-evans/create-pull-request@v6
        with:
          branch: version/${{ github.ref_name }}
          commit-message: ${{ github.ref_name }}
          title: Bump version to ${{ github.ref_name }}
          body: Automated pull request triggered by a new release.
          labels: new-release,ignore-for-release
          base: main
          delete-branch: true
          draft: false
      - name: Enable Pull Request Automerge
        run: gh pr merge --merge --auto "1"
        env:
          GH_TOKEN: ${{ secrets.PAT_WORKFLOW }}
      - name: Build
        run: echo ${{ github.sha }} > Release.txt
      - name: Test
        run: cat Release.txt
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: Release.txt
