name: Main

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"
jobs:
  build:
    runs-on: ubuntu-latest
    name: Bump version
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get next version
        uses: MiguelRipoll23/get-next-version@v3.0.0
        id: get-next-version
      - name: Change version in Cargo.toml
        run: |
          # Change version in Cargo.toml, only replace the first occurrence -> @see https://sed.js.org/
          sed -i '0,/version = \".*\"/s//version = "${{ env.NEXT_VERSION }}"/' Cargo.toml
        env:
          NEXT_VERSION: ${{ steps.get-next-version.outputs.next-version }}
      - name: Create pull request
        uses: peter-evans/create-pull-request@v6
        with:
          branch: version/${{ steps.get-next-version.outputs.next-version }}
          commit-message: ${{ steps.get-next-version.outputs.next-version }}
          title: Bump version to ${{ steps.get-next-version.outputs.next-version }}
          body: Automated pull request triggered by a new release.
          labels: new-release,ignore-for-release
          draft: true
      - name: Build
        run: echo ${{ github.sha }} > Release.txt
      - name: Test
        run: cat Release.txt
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: Release.txt
